### ISSUE TITLE
[manjaro] crash

### ISSUE THREAD

**Issue by micsuka** [linuxdeepin/dde-control-center#226]
it just crashes, a few times per day...
I can see this message in the log:

```
Jun 10 16:48:22 micsalaptop com.deepin.dde.ControlCenter[1148]: 2019-06-10, 16:48:22.265 [Debug  ] [                                                         0] virtual SettingsWidget::~SettingsWidget() I'm gone!!!
Jun 10 16:48:22 micsalaptop com.deepin.dde.ControlCenter[1148]: 2019-06-10, 16:48:22.275 [Fatal  ] [                                                         0] QThread: Destroyed while thread is still running
```

I have this call stack:
```
#0  0x00007f4b3bfca82f in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f4b36ea0b40 (LWP 10864))]
(gdb) where
#0  0x00007f4b3bfca82f in raise () at /usr/lib/libc.so.6
#1  0x00007f4b3bfb5672 in abort () at /usr/lib/libc.so.6
#2  0x00007f4b3dba8389 in  () at /usr/lib/libdtkcore.so.2
#3  0x00007f4b3dbc4bd4 in Dtk::Core::Logger::write(QDateTime const&, Dtk::Core::Logger::LogLevel, char const*, int, char const*, char const*, QString const&) () at /usr/lib/libdtkcore.so.2
#4  0x00007f4b3dbc4c4b in Dtk::Core::Logger::write(Dtk::Core::Logger::LogLevel, char const*, int, char const*, char const*, QString const&) () at /usr/lib/libdtkcore.so.2
#5  0x00007f4b3dbc4d54 in  () at /usr/lib/libdtkcore
[core.zip](https://github.com/linuxdeepin/dde-control-center/files/3274968/core.zip)
.so.2
#6  0x00007f4b3c4ff456 in  () at /usr/lib/libQt5Core.so.5
#7  0x00007f4b3c4ff5f9 in  () at /usr/lib/libQt5Core.so.5
#8  0x00007f4b3c4ce7e2 in QMessageLogger::fatal(char const*, ...) const () at /usr/lib/libQt5Core.so.5
#9  0x00007f4b3c4cf045 in  () at /usr/lib/libQt5Core.so.5
#10 0x00007f4b3c5063ca in QThread::~QThread() () at /usr/lib/libQt5Core.so.5
#11 0x00007f4b3c6ec08b in QObjectPrivate::deleteChildren() () at /usr/lib/libQt5Core.so.5
#12 0x00007f4b3c6f4f95 in QObject::~QObject() () at /usr/lib/libQt5Core.so.5
#13 0x00007f4b3d31af8a in dde::network::NetworkModel::~NetworkModel() () at /usr/lib/libdde-network-utils.so.1
#14 0x00007f4b3c6eeaa1 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#15 0x00007f4b3d678da4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#16 0x00007f4b3d6803c1 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#17 0x00007f4b3dd75ca9 in Dtk::Widget::DApplication::notify(QObject*, QEvent*) () at /usr/lib/libdtkwidget.so.2
#18 0x00007f4b3c6c3849 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#19 0x00007f4b3c6c6928 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#20 0x00007f4b3c719394 in  () at /usr/lib/libQt5Core.so.5
#21 0x00007f4b3b7ec90f in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#22 0x00007f4b3b7ee869 in  () at /usr/lib/libglib-2.0.so.0
#23 0x00007f4b3b7ee8ae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#24 0x00007f4b3c718969 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#25 0x00007f4b3c6c24dc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#26 0x00007f4b3c6ca596 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#27 0x00005596549a6e4c in main ()
(gdb) 
```
the core files and the binary + libQt5Core, libdtkcore are attached...
[core.zip](https://github.com/linuxdeepin/dde-control-center/files/3274970/core.zip)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
